# .pre-commit-config.yaml
---
repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.0
    hooks:
      - id: ansible-lint
        args: ["--skip-list", "meta-no-directive"]  # опционально, можно убрать
        types: [yaml]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.82.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.12
        files: \.py$

  - repo: https://github.com/PyCQA/isort
    rev: 6.13.0
    hooks:
      - id: isort
        files: \.py$
