
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - ci-net
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_JAVA_OPTS=-Xmx1024m -Xms512m
      - SONAR_ES_JAVA_OPTS=-Xmx1024m -Xms512m
    volumes:
      - ./sonarqube_home/data:/opt/sonarqube/data
      - ./sonarqube_home/extensions:/opt/sonarqube/extensions
      - ./sonarqube_home/logs:/opt/sonarqube/logs
    networks:
      - ci-net
    restart: always

volumes:
  jenkins_home:
  sonarqube_home:

networks:
  ci-net:
